spring.application.name=ctt-triage

spring.profiles.active=dev

#this model is used to decide wether a comment should become a ticket
huggingface.decider.url=https://router.huggingface.co/hf-inference/models/facebook/bart-large-mnli

#the confidence threshold when should a comment become a ticket
ticket.threshold=0.5

#this model does everything else- decides on how many tickets, what categories, and generates the ticket summary
huggingface.generator.url=https://router.huggingface.co/v1/chat/completions